## （七）Python Numpy 高效数据处理


In [9]:
import numpy as np
np.version.version
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [7]:
#构建一维数组
n1=np.array([1,2,3])
n1.shape   #3 列

(3,)

In [11]:
n2=np.array([[1,2,3],[4,5,6]])
n2.shape  # (2,3)  2 行，3列

(2, 3)

In [12]:
np.arange(15,20,0.1)

array([15. , 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. ,
       16.1, 16.2, 16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 16.9, 17. , 17.1,
       17.2, 17.3, 17.4, 17.5, 17.6, 17.7, 17.8, 17.9, 18. , 18.1, 18.2,
       18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3,
       19.4, 19.5, 19.6, 19.7, 19.8, 19.9])

In [19]:
np.arange(2,3,0.1) #起点，终点，步长

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [18]:
np.linspace(1,20,10) # 起点，终点，期间内有几个元素

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [15]:
np.array((range(5,10),range(5,10)))

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [23]:
tx=np.linspace(1,20,10)
tx

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [24]:
tx.shape

(10,)

In [20]:
#空矩阵  不清空数据 
np.empty((6,6))

array([[2.15813086e-314, 2.14589380e-314, 2.15892189e-314,
        2.15818539e-314, 2.14443549e-314, 2.15892179e-314],
       [2.14437328e-314, 2.15815816e-314, 2.15873956e-314,
        2.15898570e-314, 2.15898573e-314, 2.15898576e-314],
       [2.15898470e-314, 2.15898579e-314, 2.15898589e-314,
        2.15877077e-314, 2.14510370e-314, 2.15892182e-314],
       [2.15898592e-314, 2.15898601e-314, 2.14446673e-314,
        2.15892198e-314, 2.15892204e-314, 2.15898614e-314],
       [2.15898617e-314, 2.14429043e-314, 2.15838134e-314,
        2.14513380e-314, 2.14422921e-314, 2.14422974e-314],
       [2.14470425e-314, 2.14422415e-314, 2.14429697e-314,
        2.14453122e-314, 2.15898645e-314, 2.15898652e-314]])

In [21]:
np.empty((6,6)).shape

(6, 6)

In [22]:
rand:返回均匀分布随机数
randn：返回正态分布随机数

(10,)

In [26]:
#随机打乱矩阵 shuffle 洗牌
ar=np.arange(10)
np.random.shuffle(ar)
ar

array([5, 0, 1, 3, 6, 4, 9, 7, 8, 2])

In [53]:
t1=np.random.randn(3,5)
print(t1)
t1[[2],[0,2]]

[[-1.41300823  0.83080416  0.8338588   0.37012538 -1.66716133]
 [-0.49892749 -1.62940746  1.93862815  0.55173518  0.7312776 ]
 [-0.87753017  0.05417805 -1.00731913 -0.59918284 -0.61549474]]


array([-0.87753017, -1.00731913])

In [56]:
bool_a=t1>0
print(bool_a)
print(t1[bool_a])

[[False  True  True  True False]
 [False False  True  True  True]
 [False  True False False False]]
[0.83080416 0.8338588  0.37012538 1.93862815 0.55173518 0.7312776
 0.05417805]


In [27]:
r1=np.random.randn(3,5)
r1.fill(7)
r1

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [50]:
r1[1:,:]

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [51]:
r1[[2],[0,2]]

array([7., 7.])

In [28]:
ar=np.arange(10)
np.random.shuffle(ar)
ar

array([0, 4, 1, 2, 8, 7, 3, 6, 5, 9])

In [30]:
np.random.shuffle(ar)  #打乱 ar
ar

array([3, 0, 9, 2, 1, 7, 5, 6, 8, 4])

In [29]:
np.round(np.linspace(1,10,100),2)

array([ 1.  ,  1.09,  1.18,  1.27,  1.36,  1.45,  1.55,  1.64,  1.73,
        1.82,  1.91,  2.  ,  2.09,  2.18,  2.27,  2.36,  2.45,  2.55,
        2.64,  2.73,  2.82,  2.91,  3.  ,  3.09,  3.18,  3.27,  3.36,
        3.45,  3.55,  3.64,  3.73,  3.82,  3.91,  4.  ,  4.09,  4.18,
        4.27,  4.36,  4.45,  4.55,  4.64,  4.73,  4.82,  4.91,  5.  ,
        5.09,  5.18,  5.27,  5.36,  5.45,  5.55,  5.64,  5.73,  5.82,
        5.91,  6.  ,  6.09,  6.18,  6.27,  6.36,  6.45,  6.55,  6.64,
        6.73,  6.82,  6.91,  7.  ,  7.09,  7.18,  7.27,  7.36,  7.45,
        7.55,  7.64,  7.73,  7.82,  7.91,  8.  ,  8.09,  8.18,  8.27,
        8.36,  8.45,  8.55,  8.64,  8.73,  8.82,  8.91,  9.  ,  9.09,
        9.18,  9.27,  9.36,  9.45,  9.55,  9.64,  9.73,  9.82,  9.91,
       10.  ])

In [30]:
d1=np.array([1,2,3,4,5])
d1
print(d1.dtype)

int64


In [37]:
d1.astype(np.float32) #类型强转

array([1., 2., 3., 4., 5.], dtype=float32)

In [383]:
np.random.rand((3,2),dtype=np.float32)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [36]:
np.round((1,10,100),2)

array([  1,  10, 100])

In [42]:
d1.size

5

In [40]:
d1.ndim # 二维

1

In [69]:
r2=np.ones([3,4,5])
r2.ndim

3

In [70]:
r2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [83]:
r3=np.array((range(5,10),range(5,10)))
r3

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [85]:
r3[[0],[0,1]]

array([5, 6])

In [88]:
r3[1:,2:]

array([[7, 8, 9]])

In [95]:
bool_a=r3>7
bool_a

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True]])

In [96]:
r3[bool_a]

array([8, 9, 8, 9])

In [101]:
a=np.array((range(0,5),range(1,6)))
a

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5]])

In [104]:
a[1:,[0,2,3]]

array([[1, 3, 4]])

In [139]:
a=np.array((range(0,6),range(2,7),range(10,20)))
a

array([range(0, 6), range(2, 7), range(10, 20)], dtype=object)

In [140]:
a=np.array((range(0,5),range(1,6), range(2,7)))
a

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [151]:
a = np.array(range(56))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [155]:
a = [i for i in range(56) if i % 10 <= 5]
a

[0,
 1,
 2,
 3,
 4,
 5,
 10,
 11,
 12,
 13,
 14,
 15,
 20,
 21,
 22,
 23,
 24,
 25,
 30,
 31,
 32,
 33,
 34,
 35,
 40,
 41,
 42,
 43,
 44,
 45,
 50,
 51,
 52,
 53,
 54,
 55]

In [156]:
a = np.array(a)

In [157]:
a

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24,
       25, 30, 31, 32, 33, 34, 35, 40, 41, 42, 43, 44, 45, 50, 51, 52, 53,
       54, 55])

In [169]:
a=a.reshape(6, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [170]:
a.shape

(6, 6)

In [171]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [172]:
mask=np.array([1,0,1,0,1],dtype=np.bool)
mask

array([ True, False,  True, False,  True])

In [175]:
a[0,3:5]

array([3, 4])

In [176]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [177]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [178]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [179]:
for i in a:
    print(i)

[0 1 2 3 4 5]
[10 11 12 13 14 15]
[20 21 22 23 24 25]
[30 31 32 33 34 35]
[40 41 42 43 44 45]
[50 51 52 53 54 55]


In [182]:
np.arange(16).reshape(2,8).shape

(2, 8)

In [ ]:
a = [i for i in range(56) if i % 10 <= 5]

In [212]:
a = [i for i in range(56) if i % 10 <= 5]
a = np.array(a)
a = a.reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [193]:
a = [i for i in range(56) if i % 10 <= 5]
a = np.array(a)
a = a.reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [217]:
x = np.linspace(-1,1,12)
x.shape
x

array([-1.        , -0.81818182, -0.63636364, -0.45454545, -0.27272727,
       -0.09090909,  0.09090909,  0.27272727,  0.45454545,  0.63636364,
        0.81818182,  1.        ])

In [218]:
x[:,np.newaxis]

array([[-1.        ],
       [-0.81818182],
       [-0.63636364],
       [-0.45454545],
       [-0.27272727],
       [-0.09090909],
       [ 0.09090909],
       [ 0.27272727],
       [ 0.45454545],
       [ 0.63636364],
       [ 0.81818182],
       [ 1.        ]])

In [219]:
x.shape

(12,)

In [220]:
x[:,np.newaxis].shape

(12, 1)

In [221]:
x[np.newaxis,:].shape

(1, 12)

In [225]:
x=x.reshape(2,2,3)
x

array([[[-1.        , -0.81818182, -0.63636364],
        [-0.45454545, -0.27272727, -0.09090909]],

       [[ 0.09090909,  0.27272727,  0.45454545],
        [ 0.63636364,  0.81818182,  1.        ]]])

In [230]:
#转置
x=x.transpose()
x

array([[[-1.        ,  0.09090909],
        [-0.45454545,  0.63636364]],

       [[-0.81818182,  0.27272727],
        [-0.27272727,  0.81818182]],

       [[-0.63636364,  0.45454545],
        [-0.09090909,  1.        ]]])

In [231]:
x.shape

(3, 2, 2)

In [235]:
x=x.flatten()
x.shape
x.ndim

1

In [243]:
n1=np.array([[1,2],[3,4]])
n2=np.array([[5,6],[7,8]])
print(n1)
print(n2)
n1+n2

Pretty printing has been turned OFF
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

In [244]:
#1*5+2*7
n1.dot(n2)

array([[19, 22],
       [43, 50]])

In [280]:
x=np.arange(10)
np.random.shuffle(x)
x.shape=2,5
x

array([[8, 6, 4, 1, 5],
       [2, 7, 9, 0, 3]])

In [281]:
np.max(x)

9

In [282]:
np.max(x,axis=0)

array([8, 7, 9, 1, 5])

In [283]:
np.min(x,axis=1)

array([1, 0])

In [302]:
q=np.random.randn(8)*10
q

array([ 5.76459013, -0.40737158, 23.20155983,  8.92473537,  7.14690647,
       -5.35625798, 10.03987065,  2.9615463 ])

In [290]:
q.sort()
print(q)

[-18.58946408 -16.68642511  -9.36777253  -4.59147354   0.34920188
   2.60875243   6.83651755  15.1224943 ]


In [303]:
np.sort(q,axis=0)

array([-5.35625798, -0.40737158,  2.9615463 ,  5.76459013,  7.14690647,
        8.92473537, 10.03987065, 23.20155983])

In [305]:
q.shape=4,2
q

array([[ 5.76459013, -0.40737158],
       [23.20155983,  8.92473537],
       [ 7.14690647, -5.35625798],
       [10.03987065,  2.9615463 ]])

In [307]:
s=np.ones([4,2])
s

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [308]:
q

array([[ 5.76459013, -0.40737158],
       [23.20155983,  8.92473537],
       [ 7.14690647, -5.35625798],
       [10.03987065,  2.9615463 ]])

In [309]:
s+q

array([[ 6.76459013,  0.59262842],
       [24.20155983,  9.92473537],
       [ 8.14690647, -4.35625798],
       [11.03987065,  3.9615463 ]])

In [318]:
q+3

array([[ 8.76459013,  2.59262842],
       [26.20155983, 11.92473537],
       [10.14690647, -2.35625798],
       [13.03987065,  5.9615463 ]])

In [321]:
a=np.arange(16)
a=np.reshape(a,(2,-1))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [324]:
np.reshape(a,(4,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### l1=[[1,2,3],[4,5,6]]，对每个元素 +1 操作。
- python循环
- map函数
- numpy计算

In [328]:
l1=[[1,2,3],[4,5,6]]
print(len(l1))
print(len(l1[0]))
for i in range(len(l1)):
    for j in range(len(l1[i])):
        l1[i][j] += 1
        
l1

2
3


[[2, 3, 4], [5, 6, 7]]

In [345]:
l1=[[1,2,3],[4,5,6]]


TypeError: can only concatenate list (not "int") to list

In [347]:
l1=np.array(l1)
l1+1

array([[2, 3, 4],
       [5, 6, 7]])

#### 对 arr = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]] 进行行列转置
- python 列表表达式
- numpy 进行转置

In [349]:
arr = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]] 
print(arr)
print(list(map(list,zip(*arr))))

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]]


In [351]:
a=np.array(arr)
a.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

l1 = [[1,2,3],[4,5,6]]
- python，按行和列进行求和
- numpy，按行和列进行求和

In [354]:
l1 = [[1,2,3],[4,5,6]]
print(list(map(sum,l1))) #行
print(list(map(sum,list(map(list,zip(*l1)))))) #列

[6, 15]
[5, 7, 9]


In [356]:
a=np.array(l1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [358]:
b=np.sum(l1,axis=0)
b

array([5, 7, 9])

In [359]:
b=np.sum(l1,axis=1)
b

array([ 6, 15])

#### NDArray 创建与属性

使用numpy创建一个多维数组，请输出以下属性：
- 该数组的形状
- 该数组的维度
- 该数组的元素个数
- 该数组的数据类型

In [386]:
a=np.array(range(20))
print(a)
np.random.shuffle(a)
print(a)
a=a.reshape(4,5)
print('形状',a)
print('维度',a.shape)
print('元素个数',a.size)
print('数据类型',a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[14 16  7 18 10 17  1  5  4  9 15  2  0  6 19  8 11  3 12 13]
形状 [[14 16  7 18 10]
 [17  1  5  4  9]
 [15  2  0  6 19]
 [ 8 11  3 12 13]]
维度 (4, 5)
元素个数 20
数据类型 int64


In [387]:
a=a.astype(np.float32)
a

array([[14., 16.,  7., 18., 10.],
       [17.,  1.,  5.,  4.,  9.],
       [15.,  2.,  0.,  6., 19.],
       [ 8., 11.,  3., 12., 13.]], dtype=float32)

In [388]:
print('形状',a)
print('维度',a.shape)
print('元素个数',a.size)
print('数据类型',a.dtype)

形状 [[14. 16.  7. 18. 10.]
 [17.  1.  5.  4.  9.]
 [15.  2.  0.  6. 19.]
 [ 8. 11.  3. 12. 13.]]
维度 (4, 5)
元素个数 20
数据类型 float32


In [389]:
a[1:,2:]

array([[ 5.,  4.,  9.],
       [ 0.,  6., 19.],
       [ 3., 12., 13.]], dtype=float32)

#### NDArray 的访问
创建一个包含从数字 1 到 60 的数组，并将于其形状变为 (3,2,10) 的三维数组，并按如下要求访问这个三维数组：
- 访问第 0 维中第 2 个元素的所有信息
- 访问第 0 维中所有元素的全部第 0 个维度的行，和最后一个维度的列 6-7 列
- 将该数组降维至二维，形状自定义
- 打乱矩阵内元素的顺序
- 按列维度进行排序
- 将降维后的数组进行行列转置
- 将转至后的数组展平至一维数组

In [411]:
b = np.array(range(1,61))
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [412]:
b = b.reshape(3,2,10)
b

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]])

In [396]:
b[:,0,2]

array([ 3, 23, 43])

In [397]:
b[:,0,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [401]:
b[:,-1,:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [400]:
b[:,-1,[6,7]]

array([[17, 18],
       [37, 38],
       [57, 58]])

In [413]:
b = b.reshape(2,5,-1)
b

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])

In [414]:
np.random.shuffle(b)
b

array([[[31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]],

       [[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]])

In [415]:
b = b.transpose()
b

array([[[31,  1],
        [37,  7],
        [43, 13],
        [49, 19],
        [55, 25]],

       [[32,  2],
        [38,  8],
        [44, 14],
        [50, 20],
        [56, 26]],

       [[33,  3],
        [39,  9],
        [45, 15],
        [51, 21],
        [57, 27]],

       [[34,  4],
        [40, 10],
        [46, 16],
        [52, 22],
        [58, 28]],

       [[35,  5],
        [41, 11],
        [47, 17],
        [53, 23],
        [59, 29]],

       [[36,  6],
        [42, 12],
        [48, 18],
        [54, 24],
        [60, 30]]])

In [416]:
b = b.flatten()
b

array([31,  1, 37,  7, 43, 13, 49, 19, 55, 25, 32,  2, 38,  8, 44, 14, 50,
       20, 56, 26, 33,  3, 39,  9, 45, 15, 51, 21, 57, 27, 34,  4, 40, 10,
       46, 16, 52, 22, 58, 28, 35,  5, 41, 11, 47, 17, 53, 23, 59, 29, 36,
        6, 42, 12, 48, 18, 54, 24, 60, 30])

#### 拼接和切分 NDArray 对象
- 先建立两个矩阵 arr1 = [[1,2,3],[4,5,6]] 和 arr2 = [[7,8,9],[10,11,12]]
- 对两个矩阵进行横向连接，并输出结果
- 对两个矩阵进行纵向拼接，赋值给 arr3 并输出结果
- 对 arr3 按列进行分割为 3 个新元素并输出
- 对 arr3 按行进行分割为 2 个新元素并输出
- 将 arr3 转换为 python 列表，并指定数据类型为 int

In [418]:
arr1 = [[1,2,3],[4,5,6]] 
arr2 = [[7,8,9],[10,11,12]]
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [423]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [425]:
np.hsplit(arr3,3)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]

In [426]:
np.vsplit(arr3,2)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]

In [431]:
arr3 = np.transpose(arr3)
arr3

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [434]:
arr3 = arr3.astype(np.int32)
arr3

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]], dtype=int32)

In [435]:
arr3.dtype

dtype('int32')

#### 数据导入导出
- 生成一个随机矩阵，形状为 (3,5)
- 将其第 2 行第 4 列的元素修改为 998
- 保存至本地文件 random_matrix.txt
- 并尝试从这个文件中载入并验证修改是否正确

In [447]:
a = np.random.rand(15)
a = a.reshape(3,5)
a

array([[0.70009147, 0.44357375, 0.06854153, 0.86164109, 0.55513638],
       [0.56643289, 0.70957604, 0.53115053, 0.19055486, 0.87092147],
       [0.56401849, 0.57770854, 0.40282594, 0.12581623, 0.2265912 ]])

In [453]:
a[[1],[4]] = 998
a

array([[7.00091470e-01, 4.43573752e-01, 6.85415334e-02, 8.61641089e-01,
        5.55136375e-01],
       [5.66432888e-01, 7.09576042e-01, 5.31150532e-01, 1.90554860e-01,
        9.98000000e+02],
       [5.64018492e-01, 5.77708538e-01, 4.02825938e-01, 1.25816232e-01,
        2.26591196e-01]])

In [454]:
np.savetxt('random_matrix',a)

In [456]:
b = np.loadtxt('random_matrix')
b[[1],[4]]

array([998.])

#### 使用 numpy 实现 softmax
- 计算指数，并安全处理避免数字过大
- 按行求和
- 每行均除以计算的和

#### 股票相关统计量计算
- 读入的给定的 ibm 股价数据中的收盘价及成交量
- 计算成交量加权平均价 VWAP （收盘价）
- 计算时间加权平均价 TWAP（收盘价）
- 找出 IBM 股票收盘价的极差
- 计算其收盘价的中位数，均值及方差
- 计算股票的收益率（简单收益率与对数收益率）
- 计算对数收益收益率大于 1% 的天数由多少？

In [466]:
c,v = np.loadtxt('ibm.txt',delimiter='\t',usecols=(5,6),unpack=True,skiprows=1)
print(c)
print(v)

[184.1 183.1 184.  ...  86.3  85.5  86.9]
[2867600. 2597900. 3487200. ... 7624000. 5928000. 5168400.]


In [463]:
np.average(c,weights=v)

106.4904345988427

In [464]:
t=np.arange(len(c))
np.average(c,weights=t)

97.77512733963539

In [467]:
np.ptp(c)

205.0

In [468]:
np.mean(c)

110.63084231682807

In [469]:
np.median(c)

102.2

In [470]:
np.var(c)

1539.727687523647

In [472]:
c = c[:-1] #转置
c

array([184.1, 183.1, 184. , ...,  85.8,  84.9,  86.3])